//nolint:revive
package enforcementpoints

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points"
	stateClient0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/virtual_network_appliance_clusters"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type VirtualNetworkApplianceClusterClientContext utl.ClientContext

func NewVirtualNetworkApplianceClustersClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *VirtualNetworkApplianceClusterClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewVirtualNetworkApplianceClustersClient(connector)

	default:
		return nil
	}
	return &VirtualNetworkApplianceClusterClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c VirtualNetworkApplianceClusterClientContext) Delete(siteIdParam string, enforcementpointIdParam string, virtualNetworkApplianceClusterIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.VirtualNetworkApplianceClustersClient)
		err = client.Delete(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c VirtualNetworkApplianceClusterClientContext) Get(siteIdParam string, enforcementpointIdParam string, virtualNetworkApplianceClusterIdParam string) (model0.VirtualNetworkApplianceCluster, error) {
	var obj model0.VirtualNetworkApplianceCluster
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.VirtualNetworkApplianceClustersClient)
		obj, err = client.Get(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c VirtualNetworkApplianceClusterClientContext) List(siteIdParam string, enforcementpointIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.VirtualNetworkApplianceClusterListResult, error) {
	var err error
	var obj model0.VirtualNetworkApplianceClusterListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.VirtualNetworkApplianceClustersClient)
		obj, err = client.List(siteIdParam, enforcementpointIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c VirtualNetworkApplianceClusterClientContext) Patch(siteIdParam string, enforcementpointIdParam string, virtualNetworkApplianceClusterIdParam string, virtualNetworkApplianceClusterParam model0.VirtualNetworkApplianceCluster) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.VirtualNetworkApplianceClustersClient)
		err = client.Patch(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam, virtualNetworkApplianceClusterParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c VirtualNetworkApplianceClusterClientContext) Update(siteIdParam string, enforcementpointIdParam string, virtualNetworkApplianceClusterIdParam string, virtualNetworkApplianceClusterParam model0.VirtualNetworkApplianceCluster) (model0.VirtualNetworkApplianceCluster, error) {
	var err error
	var obj model0.VirtualNetworkApplianceCluster

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.VirtualNetworkApplianceClustersClient)
		obj, err = client.Update(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam, virtualNetworkApplianceClusterParam)

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

type VirtualNetworkApplianceClusterStateClientContext struct {
	Client     interface{}
	ClientType utl.ClientType
}

func NewVirtualNetworkApplianceClusterStateClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *VirtualNetworkApplianceClusterStateClientContext {
	switch sessionContext.ClientType {
	case utl.Local:
		return &VirtualNetworkApplianceClusterStateClientContext{
			Client:     stateClient0.NewStateClient(connector),
			ClientType: sessionContext.ClientType,
		}
	default:
		return nil
	}
}

func (c VirtualNetworkApplianceClusterStateClientContext) Get(siteIdParam string, enforcementpointIdParam string, virtualNetworkApplianceClusterIdParam string) (model0.VirtualNetworkApplianceClusterState, error) {
	var obj model0.VirtualNetworkApplianceClusterState

	switch c.ClientType {
	case utl.Local:
		client := c.Client.(stateClient0.StateClient)
		return client.Get(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam)
	default:
		return obj, errors.New("invalid infrastructure for model")
	}
}
